# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: 2026 Moritz Voss
class_name TweensGdTypes
extends RefCounted

const INFINITE := -1
enum Fill { NONE = 0, APPLY_FROM_DURING_DELAY = 1, RETAIN_FINAL_VALUE = 2, BOTH = 3 }
enum Process { PROCESS, PHYSICS }
enum Pause { BOUND, SCENE_TREE, ALWAYS }
enum State { DELAYED, PLAYING, INTERVAL, COMPLETED, CANCELLED, FAULTED }
enum Reason { COMPLETED, CANCELLED, TARGET_FREED, OWNER_EXITED, RUNNER_DISPOSED, FAILED, WAIT_CANCELLED }
enum BlendType { MAKIMA, HERMITE, SMOOTH_STEP, LINEAR }
enum Ease {
	LINEAR = 0,
	SINE_IN = 10, SINE_OUT, SINE_IN_OUT,
	QUAD_IN = 20, QUAD_OUT, QUAD_IN_OUT,
	CUBIC_IN = 30, CUBIC_OUT, CUBIC_IN_OUT,
	QUART_IN = 40, QUART_OUT, QUART_IN_OUT,
	QUINT_IN = 50, QUINT_OUT, QUINT_IN_OUT,
	EXPO_IN = 60, EXPO_OUT, EXPO_IN_OUT,
	CIRC_IN = 70, CIRC_OUT, CIRC_IN_OUT,
	BACK_IN = 80, BACK_OUT, BACK_IN_OUT,
	ELASTIC_IN = 90, ELASTIC_OUT, ELASTIC_IN_OUT,
	BOUNCE_IN = 100, BOUNCE_OUT, BOUNCE_IN_OUT,
	SMOOTH_STEP = 110, SMOOTHER_STEP = 120,
}
