<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <GodotProjectDir>../project</GodotProjectDir>
    <TwoDogRequireImport>true</TwoDogRequireImport>
    <TwoDogRemoveDuplicateGodotAnalyzers>true</TwoDogRemoveDuplicateGodotAnalyzers>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="2dog.xunit" Version="$(TwoDogVersion)" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.*" />
    <PackageReference Include="xunit.v3" Version="3.*" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.*" />
    <Using Include="Xunit" />
    <Content Include="xunit.runner.json" CopyToOutputDirectory="PreserveNewest" />
    <ProjectReference Include="../project/tutorial.csproj" />
  </ItemGroup>
</Project>
