// SPDX-License-Identifier: MIT
// SPDX-FileCopyrightText: 2026 Moritz Voss
using System;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace tweens.gd.Generators;

/// <summary>Generates typed array-channel entry points and literal-friendly vector keys.</summary>
[Generator(LanguageNames.CSharp)]
public sealed class KeyframeApiGenerator : IIncrementalGenerator
{
    private const string Header = "// SPDX-License-Identifier: MIT\n// SPDX-FileCopyrightText: 2026 Moritz Voss\n\n// <auto-generated />\n#nullable enable\n\nnamespace tweens.gd;\n\n";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static output =>
        {
            output.AddSource("KeyframeValues.g.cs", SourceText.From(Values(), Encoding.UTF8));
        });
        var extensions = context.CompilationProvider.Select(static (compilation, token) => Extensions(compilation, token));
        context.RegisterSourceOutput(extensions, static (output, source) =>
            output.AddSource("KeyframeExtensions.g.cs", SourceText.From(source, Encoding.UTF8)));
    }

    private static string Values()
    {
        var source = new StringBuilder(Header);
        foreach (var dimension in new[] { 2, 3 })
            foreach (var scale in new[] { false, true })
            {
                var name = (scale ? "Scale" : "Point") + dimension;
                var vector = "global::Godot.Vector" + dimension;
                source.Append("/// <summary>A ").Append(dimension).Append("-component ").Append(scale ? "scale" : "position or rotation").Append(" key.</summary>\n")
                    .Append("public readonly record struct ").Append(name).Append('(').Append(vector).Append(" Value)\n{\n")
                    .Append("    /// <summary>Converts a Godot vector.</summary>\n    public static implicit operator ").Append(name)
                    .Append('(').Append(vector).Append(" value) => new(value);\n");
                foreach (var type in new[] { "float", "double" })
                {
                    var axes = new[] { "X", "Y", "Z" }.Take(dimension).ToArray();
                    source.Append("    /// <summary>Converts a tuple of components.</summary>\n    public static implicit operator ").Append(name)
                        .Append("((").Append(string.Join(", ", axes.Select(axis => type + " " + axis))).Append(") value) => new(new ")
                        .Append(vector).Append('(').Append(string.Join(", ", axes.Select(axis => "(float)value." + axis))).Append("));\n");
                }
                if (scale)
                {
                    foreach (var type in new[] { "int", "float", "double" })
                        source.Append("    /// <summary>Uses one value on every axis.</summary>\n    public static implicit operator ").Append(name)
                            .Append('(').Append(type).Append(" value) => new(new ").Append(vector).Append('(')
                            .Append(string.Join(", ", Enumerable.Repeat("(float)value", dimension))).Append("));\n");
                    source.Append("    /// <summary>Converts a vector key.</summary>\n    public static implicit operator ").Append(name)
                        .Append("(Point").Append(dimension).Append(" value) => new(value.Value);\n");
                }
                source.Append("}\n\n");
            }
        return source.ToString().TrimEnd() + "\n";
    }

    private static string Extensions(Compilation compilation, CancellationToken token)
    {
        // The public aliases are independent of target classes. Availability and value types
        // come from Godot's properties, including keyframe-only channels such as RotationDegrees.
        var channels = new[] {
            ("x", "Position", "X"), ("y", "Position", "Y"), ("z", "Position", "Z"), ("position", "Position", ""),
            ("rotation", "Rotation", ""), ("rotationDegrees", "RotationDegrees", ""), ("scale", "Scale", ""),
            ("skew", "Skew", ""), ("quaternion", "Quaternion", ""), ("transparency", "Transparency", ""),
            ("modulate", "Modulate", ""), ("alpha", "Modulate", "A"), ("selfModulate", "SelfModulate", ""),
        };
        var factories = new StringBuilder(Header + "public static partial class Tweens\n{\n    public sealed partial class Keyframes\n    {\n");
        var extensions = new StringBuilder("public static partial class TweenExtensions\n{\n");
        foreach (var target in new[] { "CanvasItem", "Node2D", "Node3D", "GeometryInstance3D" })
        {
            if (compilation.GetTypeByMetadataName("Godot." + target) is not { } targetType) continue;
            token.ThrowIfCancellationRequested();
            var fields = channels.Select(channel => (Name: channel.Item1,
                    Property: AdapterBindings.ResolveProperty(targetType, channel.Item2, channel.Item3)))
                .Where(field => field.Property.HasValue)
                .Select(field => (field.Name, Type: KeyType(field.Property!.Value.Value, field.Name), field.Property.Value.Path)).ToArray();
            var parameters = string.Join(",\n            ", fields.Select(field => "global::System.ReadOnlySpan<" + field.Type + "> " + field.Name + " = default"));
            const string options = ",\n            Duration? duration = null, EaseType? ease = null, Interpolation interpolation = default, TweenOptions? options = null";
            factories.Append("        /// <summary>Creates reusable typed ").Append(target).Append(" channel curves.</summary>\n")
                .Append("        public static Keyframes For").Append(target).Append('(').Append(parameters).Append(options).Append(")\n        {\n")
                .Append("            var channels = new global::System.Collections.Generic.Dictionary<string, global::System.Collections.Generic.List<AnimationKey>>(global::System.StringComparer.Ordinal);\n");
            foreach (var field in fields)
                factories.Append("            AddValues(channels, \"").Append(field.Path).Append("\", ").Append(field.Name)
                    .Append(", static v => global::Godot.Variant.From(v").Append(field.Type.StartsWith("global::Godot.", StringComparison.Ordinal) ? "" : ".Value").Append("));\n");
            factories.Append("            return new(channels, duration, ease, interpolation, options);\n        }\n\n");
            extensions.Append("    /// <summary>Creates and plays typed ").Append(target).Append(" channel curves.</summary>\n")
                .Append("    public static Group Animate(this global::Godot.").Append(target).Append(" target,\n            ")
                .Append(parameters).Append(options).Append(")\n        => target.Animate(Tweens.Keyframes.For").Append(target).Append('(')
                .Append(string.Join(", ", fields.Select(field => field.Name))).Append(", duration, ease, interpolation, options));\n\n");
        }
        return factories.Append("    }\n}\n\n").Append(extensions).Append("}\n").ToString();
    }

    private static string KeyType(ITypeSymbol value, string name) => value.ToDisplayString() switch
    {
        "float" or "double" => "Real",
        "Godot.Vector2" => name == "scale" ? "Scale2" : "Point2",
        "Godot.Vector3" => name == "scale" ? "Scale3" : "Point3",
        _ => value.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
    };
}
