// SPDX-License-Identifier: MIT
// SPDX-FileCopyrightText: 2026 Moritz Voss

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using OptionsModel = (tweens.gd.Generators.EquatableArray<(string RequiredValue, string Source)> Properties, string Parameters, string Assignments, string Arguments);

namespace tweens.gd.Generators;

[Generator(LanguageNames.CSharp)]
public sealed class StructuredDefinitionGenerator : IIncrementalGenerator
{
    private static readonly SymbolDisplayFormat TypeFormat = SymbolDisplayFormat.FullyQualifiedFormat
        .WithMiscellaneousOptions(SymbolDisplayFormat.FullyQualifiedFormat.MiscellaneousOptions
            | SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier);

    private static readonly string[] Callbacks = { "OnAdd", "OnStart", "OnUpdate", "OnEnd", "OnCancel", "OnFinally" };
    private static readonly string[] Endpoints = { "From", "To", "By" };

    // Constructor arguments after `to`, in this order, like the GDScript helpers' (to, seconds, easing, delay).
    private static readonly string[] ConstructorOptions = { "Duration", "Ease", "Delay" };

    private const string Header = "// SPDX-License-Identifier: MIT\n// SPDX-FileCopyrightText: 2026 Moritz Voss\n\n"
        + "// <auto-generated />\n#nullable enable\n";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var options = context.SyntaxProvider.CreateSyntaxProvider(
                static (node, _) => node is ClassDeclarationSyntax { Identifier.ValueText: "TweenOptionsBuilder" },
                static (syntax, token) => ReadOptions(syntax, token))
            .Where(static source => source.HasValue)
            .Collect()
            .Select(static (sources, _) => sources.SingleOrDefault())
            .WithTrackingName("Options");

        // Keep symbols inside the semantic transform. Value tuples of strings give
        // downstream steps value equality, so unrelated edits don't re-emit sources.
        var definitions = context.SyntaxProvider.CreateSyntaxProvider(
                static (node, _) => node is ClassDeclarationSyntax declaration
                    && declaration.Identifier.ValueText.EndsWith("Tween", StringComparison.Ordinal),
                static (syntax, token) => ReadDefinition(syntax, token))
            .Where(static definition => definition.HasValue)
            .Select(static (definition, _) => definition!.Value)
            .WithTrackingName("Definitions");

        context.RegisterSourceOutput(definitions.Combine(options), static (output, input) =>
        {
            if (input.Right is not { } options) return;
            var (name, adapter, target, value, kind, _) = input.Left;
            output.AddSource(name + ".g.cs", SourceText.From(
                Render(name, adapter, target, value, kind, options), Encoding.UTF8));
        });

        context.RegisterSourceOutput(definitions.Collect(), static (output, definitions) =>
        {
            var scheduler = new StringBuilder(Header + "\nnamespace tweens.gd;\n\npublic sealed partial class TweenScheduler\n{\n");
            var extensions = new StringBuilder(Header + "\nnamespace tweens.gd;\n\npublic static partial class TweenExtensions\n{\n");
            foreach (var definition in definitions.OrderBy(d => d.Name, StringComparer.Ordinal))
                RenderStarts(scheduler, extensions, definition.Name, definition.Target, definition.Value, definition.Kind, definition.Resource);
            output.AddSource("TweenScheduler.g.cs", SourceText.From(scheduler.Append("}\n").ToString(), Encoding.UTF8));
            output.AddSource("TweenStarts.g.cs", SourceText.From(extensions.Append("}\n").ToString(), Encoding.UTF8));
        });

        // Extension methods live in many partial files, so read the whole type rather than one declaration.
        var extensions = context.CompilationProvider.Select(static (compilation, token) => RenderExtensions(compilation, token));
        context.RegisterSourceOutput(extensions, static (output, source) =>
        {
            if (source.Length != 0) output.AddSource("TweenExtensions.g.cs", SourceText.From(source, Encoding.UTF8));
        });

        // Roslyn can emit only C# sources. This comment-only artifact transports the shared
        // binding manifest to Generate-CSharpDefinitions.ps1; it is never shipped in the addon.
        var catalog = context.CompilationProvider.Select(static (compilation, token) => AdapterBindings.Manifest(compilation, token));
        context.RegisterSourceOutput(catalog, static (output, source) =>
            output.AddSource("TweenCatalog.g.cs", SourceText.From("/* TWEENS_GD_CATALOG\n" + source + "*/\n", Encoding.UTF8)));
    }

    private const string Span = "global::System.ReadOnlySpan<double>";
    private const string Components = "global::tweens.gd.EndpointComponents.";

    // Shorter endpoint forms with their conversion to the endpoint type. Components are doubles, so (0.5, 1) needs no
    // float suffixes. Collections such as [400, 180] are checked for their length when converted. A single number is a
    // uniform scale, and a string is an HTML color code or color name.
    private static (string Type, string Value, string Summary)[] Shorthands(string value, string name)
    {
        var uniform = name.Contains("Scale");
        switch (value)
        {
            case "global::Godot.Vector2":
                return Forms(("(double X, double Y)", "new global::Godot.Vector2((float)to.X, (float)to.Y)", "components"),
                    (Span, Components + "ToVector2(to)", "a component collection"),
                    uniform ? ("double", "new global::Godot.Vector2((float)to, (float)to)", "one value for every axis") : default);
            case "global::Godot.Vector3":
                return Forms(("(double X, double Y, double Z)",
                        "new global::Godot.Vector3((float)to.X, (float)to.Y, (float)to.Z)", "components"),
                    (Span, Components + "ToVector3(to)", "a component collection"),
                    uniform ? ("double", "new global::Godot.Vector3((float)to, (float)to, (float)to)", "one value for every axis")
                        : default);
            case "global::Godot.Vector4":
                return Forms(("(double X, double Y, double Z, double W)",
                        "new global::Godot.Vector4((float)to.X, (float)to.Y, (float)to.Z, (float)to.W)", "components"),
                    (Span, Components + "ToVector4(to)", "a component collection"));
            case "global::Godot.Color":
                return Forms(("(double R, double G, double B)",
                        "new global::Godot.Color((float)to.R, (float)to.G, (float)to.B)", "components"),
                    ("(double R, double G, double B, double A)",
                        "new global::Godot.Color((float)to.R, (float)to.G, (float)to.B, (float)to.A)", "components"),
                    (Span, Components + "ToColor(to)", "a component collection"),
                    ("string", "new global::Godot.Color(to)", "an HTML color code or color name"));
            default:
                return Array.Empty<(string, string, string)>();
        }
    }

    private static (string Type, string Value, string Summary)[] Forms(params (string Type, string Value, string Summary)[] forms)
        => forms.Where(form => form.Type is not null).ToArray();

    private static INamedTypeSymbol? ReadType(GeneratorSyntaxContext context, CancellationToken token)
    {
        var symbol = context.SemanticModel.GetDeclaredSymbol((ClassDeclarationSyntax)context.Node, token) as INamedTypeSymbol;
        if (symbol is null || symbol.ContainingType is not null
            || symbol.ContainingNamespace.ToDisplayString() != "tweens.gd") return null;
        // A partial class is one adapter, regardless of how many declarations it has.
        var first = symbol.DeclaringSyntaxReferences[0];
        return first.SyntaxTree == context.Node.SyntaxTree && first.Span == context.Node.Span ? symbol : null;
    }

    private static OptionsModel? ReadOptions(GeneratorSyntaxContext context, CancellationToken token)
    {
        var symbol = ReadType(context, token);
        if (symbol is null) return null;
        var properties = new List<(string RequiredValue, string Source)>();
        var types = new string?[ConstructorOptions.Length];
        foreach (var property in symbol.GetMembers().OfType<IPropertySymbol>())
        {
            if (property.IsStatic || property.IsIndexer
                || property.GetMethod?.DeclaredAccessibility != Accessibility.Public
                || property.SetMethod?.DeclaredAccessibility != Accessibility.Public) continue;
            var name = "@" + property.Name;
            var type = property.Type.ToDisplayString(TypeFormat);
            var requiredValue = property.GetAttributes().FirstOrDefault(attribute =>
                attribute.AttributeClass?.ToDisplayString() == "tweens.gd.TweenValueOptionAttribute")
                ?.ConstructorArguments.FirstOrDefault().Value as ITypeSymbol;
            var source = new StringBuilder();
            source.Append("    /// <inheritdoc cref=\"TweenOptions.").Append(property.Name).Append("\"/>\n")
                .Append("    public ").Append(type).Append(' ').Append(name)
                .Append(" { get => Options.").Append(name)
                .Append("; init => Options = Options with { ").Append(name).Append(" = value }; }\n");
            properties.Add((requiredValue?.ToDisplayString(TypeFormat) ?? "", source.ToString()));
            var index = Array.IndexOf(ConstructorOptions, property.Name);
            if (index >= 0) types[index] = type;
        }

        var parameters = new StringBuilder();
        var assignments = new StringBuilder();
        var arguments = new StringBuilder();
        for (var i = 0; i < ConstructorOptions.Length; i++)
        {
            if (types[i] is not { } type) continue;
            var option = ConstructorOptions[i];
            var parameter = "@" + char.ToLowerInvariant(option[0]) + option.Substring(1);
            parameters.Append(", ").Append(type).Append(' ').Append(parameter).Append(" = default");
            assignments.Append(assignments.Length == 0 ? "" : ", ").Append('@').Append(option).Append(" = ").Append(parameter);
            arguments.Append(", ").Append(parameter);
        }
        return (new EquatableArray<(string, string)>(properties), parameters.ToString(),
            assignments.Length == 0 ? "" : "        Options = new TweenOptions { " + assignments + " };\n", arguments.ToString());
    }

    private static (string Name, string Adapter, string Target, string Value, DefinitionKind Kind, bool Resource)? ReadDefinition(
        GeneratorSyntaxContext context, CancellationToken token)
    {
        var symbol = ReadType(context, token);
        if (symbol is null || symbol.IsAbstract || symbol.DeclaredAccessibility != Accessibility.Public) return null;

        var kind = GetDefinitionKind(symbol);
        if (kind is null) return null;

        for (var parent = symbol.BaseType; parent is not null; parent = parent.BaseType)
        {
            if (parent.Name != "TweenDefinition" || parent.Arity != 2
                || parent.ContainingNamespace.ToDisplayString() != "tweens.gd") continue;
            return (symbol.Name.Substring(0, symbol.Name.Length - "Tween".Length),
                symbol.ToDisplayString(TypeFormat), parent.TypeArguments[0].ToDisplayString(TypeFormat),
                    parent.TypeArguments[1].ToDisplayString(TypeFormat), kind.Value, IsResource(parent.TypeArguments[0]));
        }
        return null;
    }

    private static bool IsResource(ITypeSymbol type)
    {
        for (var current = type as INamedTypeSymbol; current is not null; current = current.BaseType)
            if (current.ToDisplayString() == "Godot.Resource") return true;
        return false;
    }

    private static void RenderStarts(StringBuilder scheduler, StringBuilder extensions, string name, string target,
        string value, DefinitionKind kind, bool resource)
    {
        var generic = kind == DefinitionKind.CustomProperty ? "<TTarget, TValue>"
            : kind == DefinitionKind.ShaderParameter ? "<TValue>" : "";
        var constraints = kind == DefinitionKind.CustomProperty ? " where TTarget : class where TValue : struct"
            : kind == DefinitionKind.ShaderParameter ? " where TValue : struct" : "";
        var definition = "Tweens." + name + generic;
        var result = "TweenInstance<" + target + ", " + value + ">";
        var add = "AddValue<" + target + ", " + value + ", " + definition + ">";
        var parameters = target + " target, in " + definition + " definition";
        const string options = "PlaybackOptions options = default";
        const string doc = "    /// <summary>Starts a concrete immutable definition without boxing it.</summary>\n";
        scheduler.Append(doc).Append("    public ").Append(result).Append(" Add").Append(generic)
            .Append('(').Append(parameters).Append(", ").Append(options).Append(')').Append(constraints)
            .Append("\n        => ").Append(add).Append("(target, in definition, ")
            .Append(resource ? "null" : "target as global::Godot.Node").Append(", null, options);\n\n");
        scheduler.Append(doc).Append("    public ").Append(result).Append(" Add").Append(generic)
            .Append('(').Append(parameters).Append(", global::Godot.Node owner, ").Append(options).Append(')').Append(constraints)
            .Append("\n    {\n        global::System.ArgumentNullException.ThrowIfNull(owner);\n        return ")
            .Append(add).Append("(target, in definition, owner, null, options);\n    }\n\n");

        if (!resource)
        {
            var nodeConstraints = kind == DefinitionKind.CustomProperty ? " where TTarget : global::Godot.Node where TValue : struct" : constraints;
            extensions.Append(doc).Append("    public static ").Append(result).Append(" Tween").Append(generic)
                .Append("(this ").Append(parameters).Append(", ").Append(options).Append(')').Append(nodeConstraints)
                .Append("\n        => TweenRuntime.GetRunner(target).Scheduler.").Append(add)
                .Append("(target, in definition, target, null, options);\n\n");
        }
        if (resource || kind == DefinitionKind.CustomProperty)
        {
            var resourceConstraints = kind == DefinitionKind.CustomProperty ? " where TTarget : global::Godot.Resource where TValue : struct" : constraints;
            extensions.Append(doc).Append("    public static ").Append(result).Append(" Tween").Append(generic)
                .Append("(this ").Append(parameters).Append(", global::Godot.SceneTree tree, global::Godot.Node? owner = null, ")
                .Append(options).Append(')').Append(resourceConstraints)
                .Append("\n        => TweenRuntime.GetRunner(tree).Scheduler.").Append(add)
                .Append("(target, in definition, owner, tree, options);\n\n");
            extensions.Append(doc).Append("    public static ").Append(result).Append(" Tween").Append(generic)
                .Append("(this ").Append(parameters).Append(", global::Godot.Node owner, ").Append(options).Append(')').Append(resourceConstraints)
                .Append("\n    {\n        TweenRuntime.ValidateOwner(owner);\n        return target.Tween(in definition, owner.GetTree(), owner, options);\n    }\n\n");
            extensions.Append(doc).Append("    public static ").Append(result).Append(" Tween").Append(generic)
                .Append("(this global::Godot.Node owner, ").Append(parameters).Append(", ").Append(options).Append(')').Append(resourceConstraints)
                .Append("\n        => target.Tween(in definition, owner, options);\n\n");
        }
    }

    private static DefinitionKind? GetDefinitionKind(INamedTypeSymbol symbol)
    {
        if (symbol.Name == "PropertyTween" && symbol.Arity == 2)
            return DefinitionKind.CustomProperty;
        if (symbol.IsSealed && symbol.Arity == 1 && symbol.Name is
            "ShaderParameterTween" or "CanvasItemInstanceShaderParameterTween" or "GeometryInstanceShaderParameterTween")
            return DefinitionKind.ShaderParameter;
        if (symbol.IsSealed && symbol.Arity == 0
            && symbol.BaseType is { Name: "PropertyTween", Arity: 2 } parent
            && parent.ContainingNamespace.ToDisplayString() == "tweens.gd"
            && symbol.InstanceConstructors.Any(constructor => constructor.Parameters.Length == 0
                && constructor.DeclaredAccessibility == Accessibility.Public))
            return DefinitionKind.BuiltIn;
        return null;
    }

    private static string Render(string name, string adapter, string target, string value, DefinitionKind kind, OptionsModel options)
    {
        var generic = kind == DefinitionKind.CustomProperty ? "<TTarget, TValue>"
            : kind == DefinitionKind.ShaderParameter ? "<TValue>" : "";
        var instance = "TweenInstance<" + target + ", " + value + ">";
        var playback = "TweenDefinition<" + target + ", " + value + ">";
        var contract = "ITweenDefinition<" + target + ", " + value + ">";
        var source = new StringBuilder();
        source.Append("/// <summary>Reusable immutable ").Append(name)
            .Append(" definition. Each start snapshots configuration; activation captures the current value.</summary>\n")
            .Append("public readonly record struct ").Append(name).Append(generic).Append(" : ").Append(contract);
        if (kind == DefinitionKind.CustomProperty) source.Append("\n    where TTarget : class where TValue : struct");
        else if (kind == DefinitionKind.ShaderParameter) source.Append("\n    where TValue : struct");
        source.Append("\n{\n    /// <summary>Shared timing, easing, and playback modes.")
            .Append(kind == DefinitionKind.BuiltIn ? "" : " Configure value-specific policies here for generic definitions.")
            .Append(" Individual option properties forward to this value.</summary>\n")
            .Append("    public TweenOptions Options { get; init; }\n");
        foreach (var property in options.Properties.Items)
            if (property.RequiredValue.Length == 0 || property.RequiredValue == value) source.Append(property.Source);
        source.Append('\n')
            .Append("    /// <inheritdoc cref=\"TweenDefinition{TTarget, TValue}.From\"/>\n")
            .Append("    public ").Append(value).Append("? From { get; init; }\n")
            .Append("    /// <inheritdoc cref=\"TweenDefinition{TTarget, TValue}.To\"/>\n")
            .Append("    public ").Append(value).Append("? To { get; init; }\n")
            .Append("    /// <inheritdoc cref=\"TweenDefinition{TTarget, TValue}.By\"/>\n")
            .Append("    public ").Append(value).Append("? By { get; init; }\n");
        // Factors default to 1 in default and new() values too, like TweenOptions.Skew.
        foreach (var endpoint in Endpoints)
            source.Append("    private readonly double? factor").Append(endpoint).Append(";\n")
                .Append("    /// <inheritdoc cref=\"TweenDefinition{TTarget, TValue}.Factor").Append(endpoint).Append("\"/>\n")
                .Append("    public double Factor").Append(endpoint).Append(" { get => factor").Append(endpoint)
                .Append(" ?? 1; init => factor").Append(endpoint).Append(" = value == 1 ? null : value; }\n")
                .Append("    /// <inheritdoc cref=\"TweenDefinition{TTarget, TValue}.Delta").Append(endpoint).Append("\"/>\n")
                .Append("    public ").Append(value).Append("? Delta").Append(endpoint).Append(" { get; init; }\n");
        foreach (var callback in Callbacks)
            source.Append("    /// <inheritdoc cref=\"TweenDefinition{TTarget, TValue}.").Append(callback).Append("\"/>\n")
                .Append("    public Action<").Append(instance).Append(callback == "OnUpdate" ? ", " + value : "")
                .Append(">? ").Append(callback).Append(" { get; init; }\n");

        // Binding parameters lead, then the endpoint and the constructor options.
        var binding = "";
        var bound = "";
        if (kind == DefinitionKind.ShaderParameter)
        {
            source.Append("\n    /// <summary>Name of the shader uniform. Resolved and validated when playback starts.</summary>\n")
                .Append("    public string Parameter { get; init; }\n");
            binding = "string parameter, ";
            bound = "        Parameter = parameter;\n";
        }
        else if (kind == DefinitionKind.CustomProperty)
        {
            source.Append("\n    /// <summary>Reads the current value from the target.</summary>\n")
                .Append("    public Func<TTarget, TValue> Getter { get; init; }\n")
                .Append("    /// <summary>Writes the interpolated value to the target.</summary>\n")
                .Append("    public Action<TTarget, TValue> Setter { get; init; }\n")
                .Append("    /// <summary>Interpolates endpoints using eased weight, which may overshoot [0, 1].</summary>\n")
                .Append("    public Func<TValue, TValue, float, TValue> Interpolate { get; init; }\n");
            binding = "Func<TTarget, TValue> getter, Action<TTarget, TValue> setter,\n"
                + "        Func<TValue, TValue, float, TValue> interpolate, ";
            bound = "        Getter = getter;\n        Setter = setter;\n        Interpolate = interpolate;\n";
        }
        // Constructor endpoints are never null; an endpoint left unset in an initializer is read at start. Float
        // endpoints take doubles, so 0.5 needs no suffix.
        var single = value == "float";
        if (binding.Length != 0)
            source.Append("\n    /// <summary>Sets the binding. Endpoints left unset are read at start.</summary>\n")
                .Append("    public ").Append(name).Append('(').Append(binding.Substring(0, binding.Length - 2)).Append(")\n    {\n")
                .Append(bound).Append("    }\n");
        source.Append("\n    /// <summary>Sets the endpoint and common timing.</summary>\n")
            .Append("    public ").Append(name).Append('(').Append(binding).Append(single ? "double" : value).Append(" to")
            .Append(options.Parameters).Append(")\n    {\n")
            .Append(bound).Append(single ? "        To = (float)to;\n" : "        To = to;\n")
            .Append(options.Assignments).Append("    }\n");
        if (kind == DefinitionKind.BuiltIn)
            foreach (var (type, conversion, summary) in Shorthands(value, name))
                source.Append("\n    /// <summary>Sets the endpoint from ").Append(summary).Append(" and common timing.</summary>\n")
                    .Append("    public ").Append(name).Append('(').Append(type).Append(" to").Append(options.Parameters)
                    .Append(")\n        : this(").Append(conversion).Append(options.Arguments).Append(") { }\n");

        source.Append('\n').Append("    ").Append(playback).Append(' ').Append(contract).Append(".CreatePlayback()\n    {\n")
            .Append("        var playback = new ").Append(adapter)
            .Append(kind == DefinitionKind.ShaderParameter ? "(Parameter)"
                : kind == DefinitionKind.CustomProperty ? "(Getter, Setter, Interpolate)" : "()")
            .Append("\n        {\n            From = From,\n            To = To,\n            By = By,\n");
        foreach (var endpoint in Endpoints)
            source.Append("            Factor").Append(endpoint).Append(" = Factor").Append(endpoint).Append(",\n")
                .Append("            Delta").Append(endpoint).Append(" = Delta").Append(endpoint).Append(",\n");
        foreach (var callback in Callbacks)
            source.Append("            ").Append(callback).Append(" = ").Append(callback).Append(",\n");
        source.Append("        };\n        Options.CopyTo(playback);\n        return playback;\n    }\n}");
        // Definitions nest in Tweens, so `using tweens.gd;` reaches them as Tweens.Name without a global namespace.
        var nested = string.Join("\n", source.ToString().Split('\n').Select(line => line.Length == 0 ? line : "    " + line));
        return Header + "using global::System;\n\nnamespace tweens.gd;\n\npublic static partial class Tweens\n{\n" + nested + "\n}\n";
    }

    // Twins of the extension methods with a shorter endpoint form, and with an easing and delay in place of configure.
    // Each forwards to the method it copies.
    private static string RenderExtensions(Compilation compilation, CancellationToken token)
    {
        if (compilation.GetTypeByMetadataName("tweens.gd.TweenExtensions") is not { } type) return "";
        var source = new StringBuilder(Header + "\nnamespace tweens.gd;\n\npublic static partial class TweenExtensions\n{\n");
        var methods = type.GetMembers().OfType<IMethodSymbol>()
            .Where(method => method.IsExtensionMethod && !method.IsGenericMethod
                && method.DeclaredAccessibility == Accessibility.Public
                && method.Parameters.All(parameter => parameter.RefKind == RefKind.None && !parameter.IsParams))
            .Select(method => (Method: method, Id: method.GetDocumentationCommentId() ?? ""))
            .OrderBy(entry => entry.Id, StringComparer.Ordinal);
        var count = 0;
        foreach (var (method, id) in methods)
        {
            token.ThrowIfCancellationRequested();
            if (method.Parameters.FirstOrDefault(parameter => parameter.Name == "to") is not { } to) continue;
            var endpoint = to.Type.ToDisplayString(TypeFormat);
            var shorthands = Shorthands(endpoint, method.Name);
            foreach (var (form, conversion, _) in shorthands)
                AppendTwin(source, "    /// <inheritdoc cref=\"" + id + "\"/>\n", method, to, form, conversion, null, ref count);
            if (method.Parameters.FirstOrDefault(parameter => parameter.Name == "configure") is not { Type: INamedTypeSymbol action } configure)
                continue;
            var summary = "    /// <summary>Starts a " + action.TypeArguments[0].Name + " and returns its playback handle.</summary>\n"
                + "    /// <remarks>Sets duration, easing, and delay before snapshotting.</remarks>\n";
            foreach (var (form, conversion, _) in shorthands.Prepend((endpoint, "@to", "")))
                AppendTwin(source, summary, method, to, form, conversion, configure, ref count);
        }
        if (count == 0) return "";
        source.Length--;
        return source.Append("}\n").ToString();
    }

    // Replaces the endpoint with another form, and configure (when given) with an easing and a delay.
    private static void AppendTwin(StringBuilder source, string documentation, IMethodSymbol method, IParameterSymbol to,
        string form, string conversion, IParameterSymbol? configure, ref int count)
    {
        count++;
        var parameters = method.Parameters.Select((parameter, index) =>
            SymbolEqualityComparer.Default.Equals(parameter, configure) ? "global::tweens.gd.EaseType @ease, global::tweens.gd.Duration @delay = default"
            : (index == 0 ? "this " : "")
                + (SymbolEqualityComparer.Default.Equals(parameter, to) ? form : parameter.Type.ToDisplayString(TypeFormat))
                + " @" + parameter.Name + DefaultValue(parameter));
        var arguments = method.Parameters.Select(parameter =>
            SymbolEqualityComparer.Default.Equals(parameter, to) ? conversion
            : SymbolEqualityComparer.Default.Equals(parameter, configure) ? "definition => { definition.Ease = @ease; definition.Delay = @delay; }"
            : "@" + parameter.Name);
        source.Append(documentation)
            .Append("    public static ").Append(method.ReturnType.ToDisplayString(TypeFormat)).Append(' ')
            .Append(method.Name).Append('(').Append(string.Join(", ", parameters)).Append(")\n        => ")
            .Append(method.Name).Append('(').Append(string.Join(", ", arguments)).Append(");\n\n");
    }

    private static string DefaultValue(IParameterSymbol parameter)
    {
        if (!parameter.HasExplicitDefaultValue) return "";
        var value = parameter.ExplicitDefaultValue;
        if (value is null) return " = default";
        var literal = SymbolDisplay.FormatPrimitive(value, quoteStrings: true, useHexadecimalNumbers: false);
        return parameter.Type.TypeKind == TypeKind.Enum
            ? " = (" + parameter.Type.ToDisplayString(TypeFormat) + ")" + literal
            : " = " + literal + (value is float ? "f" : "");
    }

    private enum DefinitionKind { BuiltIn, ShaderParameter, CustomProperty }
}
